project:
  name: "xml_vision_finetuning"
  experiment_version: "1"
  model_type: "llama3.2"
  
model:
  model_name: "637Koleshjr/case_law_finetuningunsloth_Meta-Llama-3.1-8B-Instruct-1-3-epochs-lr-2e-4"
  max_seq_length: 8192
  load_in_4bit: True

inference:
  max_new_tokens: 4096